name: Core Workflow 🎯

on:
  push:
    branches: ["**"]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit

  run-playwright-tests:
    name: Run Playwright Tests
    needs: run-unit-tests
    if: ${{ needs.run-unit-tests.result == 'success' }}
    uses: ./.github/workflows/playwright.yml
    secrets: inherit

  deploy-to-netlify:
    name: Deploy to Netlify
    uses: ./.github/workflows/netlify-deploy.yml
    needs: run-playwright-tests
    if: ${{ needs.run-playwright-tests.result == 'success' && github.ref == 'refs/heads/main' }}
    secrets: inherit
