name: Unit Tests

on:
  push: # Run on every push
    branches: ["*"]
  pull_request: # Run on every PR from any branch
    branches: ["*"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests (Jest)
        run: npm run test:unit

      - name: Upload Jest Test Coverage (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: coverage
